/**
 * Third-party integration templates for EDS. Everything here is appended to
 * `scripts/delayed.js` so it loads in the delayed phase (after LCP, non-blocking)
 * per EDS performance best practices. Heavy widgets (chat) use the facade
 * pattern - a lightweight trigger that loads the real script on first interaction.
 */

export interface IntegrationField {
	name: string;
	message: string;
	placeholder?: string;
}

export interface Integration {
	id: string;
	name: string;
	fields: IntegrationField[];
	/** Snippet appended to `scripts/delayed.js` (wrapped in a block). */
	code: (v: Record<string, string>) => string;
	/** Optional dedicated module file(s) written alongside (for exported helpers). */
	module?: (v: Record<string, string>) => Array<{ file: string; content: string }>;
}

export const INTEGRATIONS: Integration[] = [
	{
		id: "gtm",
		name: "Google Tag Manager",
		fields: [{ name: "id", message: "GTM container ID", placeholder: "GTM-XXXXXXX" }],
		// delayed.js imports the loader + page-meta, pushes page metadata, then GTM.
		code: () => `// Google Tag Manager - loaded from ./analytics.js (delayed phase, after LCP).
import { loadGTM } from './analytics.js';
import pageMetaPush from './page-meta.js';

const pageMetaReady = pageMetaPush();
pageMetaReady.then(loadGTM);`,
		module: (v) => [
			{
				file: "scripts/analytics.js",
				content: `// scripts/analytics.js - Google Tag Manager (generated by \`eds integrate gtm\`).
// The container ID comes from the \`gtm-id\` metadata, falling back to the one
// configured here. Import { trackEvent } from './analytics.js' to push events.

const FALLBACK_ID = ${JSON.stringify(v.id || "")};

function getMetadata(name) {
  const meta = document.querySelector(\`meta[name="\${name}"]\`);
  return meta ? meta.content : '';
}

function isDev() {
  const h = window.location.hostname;
  return h === 'localhost' || h === '127.0.0.1' || h.endsWith('.aem.page') || h.endsWith('.hlx.page');
}

// dataLayer must exist before anything pushes to it (trackEvent may run before loadGTM).
window.dataLayer = window.dataLayer || [];

export function trackEvent(event) {
  if (isDev()) {
    // eslint-disable-next-line no-console
    console.log('[gtm]', JSON.stringify(event, null, 2));
  }
  window.dataLayer.push(event);
}

let loaded = false;

export function loadGTM() {
  if (loaded) return;
  const raw = getMetadata('gtm-id') || FALLBACK_ID;
  if (!raw) return;
  loaded = true;

  const id = raw.startsWith('GTM-') ? raw : \`GTM-\${raw}\`;
  window.dataLayer.push({ 'gtm.start': Date.now(), event: 'gtm.js' });

  const script = document.createElement('script');
  script.async = true;
  script.src = \`https://www.googletagmanager.com/gtm.js?id=\${id}\`;
  document.head.append(script);
}
`,
			},
			{
				file: "scripts/page-meta.js",
				content: `// scripts/page-meta.js - pushes page-level metadata to the dataLayer before
// GTM initialises. Extend \`pageMeta\` with the fields your container expects.
import { trackEvent } from './analytics.js';

export default async function pageMetaPush() {
  const pageMeta = {
    event: 'page_meta',
  };

  trackEvent(pageMeta);

  return pageMeta;
}
`,
			},
		],
	},
	{
		id: "ga4",
		name: "Google Analytics 4",
		fields: [{ name: "id", message: "Measurement ID", placeholder: "G-XXXXXXXXXX" }],
		code: (v) => `// Google Analytics 4 (${v.id}) - delayed phase.
const gaScript = document.createElement('script');
gaScript.async = true;
gaScript.src = 'https://www.googletagmanager.com/gtag/js?id=${v.id}';
document.head.appendChild(gaScript);
window.dataLayer = window.dataLayer || [];
function gtag() { window.dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', '${v.id}');`,
	},
	{
		id: "chat",
		name: "Chat widget (facade)",
		fields: [
			{ name: "label", message: "Button label", placeholder: "Chat with us" },
			{ name: "src", message: "Chat widget script URL" },
		],
		code: (v) => `// Chat widget - facade pattern: load the heavy script only on first interaction.
const chatBtn = document.createElement('button');
chatBtn.type = 'button';
chatBtn.className = 'chat-facade';
chatBtn.textContent = ${JSON.stringify(v.label || "Chat")};
chatBtn.addEventListener('click', () => {
  const s = document.createElement('script');
  s.async = true;
  s.src = ${JSON.stringify(v.src || "")};
  document.body.appendChild(s);
  chatBtn.remove();
}, { once: true });
document.body.appendChild(chatBtn);`,
	},
	{
		id: "cookiebot",
		name: "Cookie consent (Cookiebot)",
		fields: [{ name: "id", message: "Cookiebot domain group ID (CBID)" }],
		code: (
			v,
		) => `// Cookiebot consent - load early in delayed; configure GTM consent mode to respect it.
const cb = document.createElement('script');
cb.id = 'Cookiebot';
cb.src = 'https://consent.cookiebot.com/uc.js';
cb.setAttribute('data-cbid', '${v.id}');
cb.async = true;
document.head.appendChild(cb);`,
	},
	{
		id: "custom",
		name: "Custom third-party script",
		fields: [{ name: "url", message: "Script URL" }],
		code: (v) => `// Custom third-party script - delayed phase.
const s = document.createElement('script');
s.async = true;
s.src = ${JSON.stringify(v.url || "")};
document.head.appendChild(s);`,
	},
];

export function integrationById(id: string): Integration | undefined {
	return INTEGRATIONS.find((i) => i.id === id);
}

/** Wrap generated code in a marked block for `scripts/delayed.js`. */
export function wrapBlock(name: string, code: string): string {
	return `\n// ── ${name} (eds integrate) ──────────────────────────────\n{\n${code
		.split("\n")
		.map((l) => (l ? `  ${l}` : l))
		.join("\n")}\n}\n`;
}
