/**
 * Instrument an EDS block's `decorate()` with dataLayer tracking - click and
 * form-submit events pushed through `trackEvent` from `scripts/analytics.js`
 * (generated by `eds integrate gtm`). Deterministic source rewrite, idempotent.
 */

export interface TrackEvents {
	click: boolean;
	submit: boolean;
}

/** Marker so re-running never double-instruments a block. */
export const TRACK_MARKER = "analytics (eds track)";

const IMPORT_LINE = "import { trackEvent } from '../../scripts/analytics.js';";

/** The instrumentation lines injected at the top of decorate(). */
export function trackSnippet(blockName: string, param: string, events: TrackEvents): string {
	const parts: string[] = [`  // --- ${TRACK_MARKER} ---`];
	if (events.click) {
		parts.push(
			`  ${param}.addEventListener('click', (ev) => {`,
			"    const el = ev.target.closest('a, button');",
			"    if (!el) return;",
			`    trackEvent({ event: 'block_click', block: '${blockName}', label: el.dataset.track || el.textContent.trim() });`,
			"  });",
		);
	}
	if (events.submit) {
		parts.push(
			`  ${param}.addEventListener('submit', () => {`,
			`    trackEvent({ event: 'form_submit', block: '${blockName}' });`,
			"  });",
		);
	}
	return parts.join("\n");
}

export interface InstrumentResult {
	js: string;
	changed: boolean;
	reason?: string;
}

/**
 * Add the `trackEvent` import and inject the tracking snippet at the top of the
 * block's `decorate()`. Returns `changed: false` with a reason when it's
 * already instrumented or no `decorate()` is found.
 */
export function instrumentJs(js: string, blockName: string, events: TrackEvents): InstrumentResult {
	if (js.includes(TRACK_MARKER)) return { js, changed: false, reason: "already instrumented" };
	if (!events.click && !events.submit) return { js, changed: false, reason: "no events selected" };

	// Find decorate() and capture its parameter name (usually `block`).
	const decorate = js.match(
		/export default (?:async )?function decorate\s*\(\s*([A-Za-z_$][\w$]*)?[^)]*\)\s*\{/,
	);
	if (!decorate || decorate.index === undefined) {
		return { js, changed: false, reason: "no `export default function decorate(...)` found" };
	}
	const param = decorate[1] || "block";

	// Add the import after the last existing import, else at the top.
	let out = js;
	if (!out.includes("scripts/analytics.js")) {
		const imports = [...out.matchAll(/^import .*$/gm)];
		if (imports.length) {
			const last = imports[imports.length - 1];
			const at = (last.index ?? 0) + last[0].length;
			out = `${out.slice(0, at)}\n${IMPORT_LINE}${out.slice(at)}`;
		} else {
			out = `${IMPORT_LINE}\n\n${out}`;
		}
	}

	// Re-find decorate in the (possibly shifted) output and inject after its `{`.
	const d2 = out.match(
		/export default (?:async )?function decorate\s*\(\s*([A-Za-z_$][\w$]*)?[^)]*\)\s*\{/,
	);
	if (!d2 || d2.index === undefined)
		return { js: out, changed: false, reason: "decorate not found" };
	const at = d2.index + d2[0].length;
	const snippet = trackSnippet(blockName, param, events);
	out = `${out.slice(0, at)}\n${snippet}\n${out.slice(at)}`;
	return { js: out, changed: true };
}
