import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import chalk from "chalk";
import { logger } from "../../lib/logger.js";
import { findProjectRoot } from "../../lib/project.js";
import { kebabCaseRegex } from "../../lib/schemas.js";

interface CreateBlockOptions {
	/** Generate the Universal Editor model. Defaults to true. */
	ueModel?: boolean;
}

/** `hero-banner` → `Hero Banner` */
function titleCase(name: string): string {
	return name
		.split("-")
		.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
		.join(" ");
}

/**
 * The Universal Editor block config (`_<name>.json`): the `definitions`,
 * `models` and `filters` that let an author drop and edit this block in UE.
 * A single rich-text field is a safe starting point authors can extend.
 */
export function ueModelFor(name: string): string {
	const title = titleCase(name);
	const model = {
		definitions: [
			{
				title,
				id: name,
				plugins: {
					xwalk: {
						page: {
							resourceType: "core/franklin/components/block/v1/block",
							template: { name: title, model: name },
						},
					},
				},
			},
		],
		models: [
			{
				id: name,
				// Starter fields showcasing good patterns (title+titleType collapse
				// into a heading; richtext for body). Extend from the full catalog —
				// see docs/universal-editor-fields.md.
				fields: [
					{
						component: "text",
						name: "title",
						label: "Title",
						valueType: "string",
					},
					{
						component: "select",
						name: "titleType",
						label: "Title Type",
						valueType: "string",
						value: "h2",
						options: [
							{ name: "H1", value: "h1" },
							{ name: "H2", value: "h2" },
							{ name: "H3", value: "h3" },
							{ name: "H4", value: "h4" },
						],
					},
					{
						component: "richtext",
						name: "text",
						value: "",
						label: "Text",
						valueType: "string",
					},
				],
			},
		],
		filters: [],
	};
	return `${JSON.stringify(model, null, 2)}\n`;
}

export async function createBlock(name: string, options: CreateBlockOptions = {}): Promise<void> {
	if (!kebabCaseRegex.test(name)) {
		logger.error(
			`Invalid block name "${name}". Use kebab-case (e.g., "hero-banner", "card-list").`,
		);
		process.exitCode = 1;
		return;
	}

	const projectRoot = findProjectRoot();
	if (!projectRoot) {
		logger.error(
			"Not inside an EDS project (no EDS project markers found). Run this from your project root.",
		);
		process.exitCode = 1;
		return;
	}

	const blocksDir = path.join(projectRoot, "blocks", name);
	if (existsSync(blocksDir)) {
		logger.error(`Block "${name}" already exists at ${blocksDir}`);
		process.exitCode = 1;
		return;
	}

	await mkdir(blocksDir, { recursive: true });

	const jsContent = `export default function decorate(block) {
  // TODO: implement ${name} block
}
`;

	const cssContent = `.${name} {
  /* TODO: style ${name} block */
}
`;

	await writeFile(path.join(blocksDir, `${name}.js`), jsContent);
	await writeFile(path.join(blocksDir, `${name}.css`), cssContent);

	// Universal Editor authoring is a first-class output — generated by default.
	const withUe = options.ueModel !== false;
	if (withUe) {
		await writeFile(path.join(blocksDir, `_${name}.json`), ueModelFor(name));
	}

	logger.success(
		`Block "${name}" created at ${chalk.cyan(path.relative(projectRoot, blocksDir))}${
			withUe ? chalk.dim(" (+ Universal Editor model)") : ""
		}`,
	);
}
