import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

/** Repo-relative path of the generated workflow. */
export const CI_WORKFLOW_PATH = ".github/workflows/eds.yml";

/**
 * GitHub Actions boilerplate for an EDS project: runs the project's own
 * lint/build (if defined) plus the eds audits as a PR gatekeeper. The audits
 * exit non-zero on problems, so a bad change fails the check.
 *
 * `if:` conditions are intentionally written without a `${{ }}` wrapper so this
 * template literal has no `${` sequences to escape.
 */
export const CI_WORKFLOW = `name: EDS checks

# Generated by aem-eds-kit (\`eds scaffold ci\`). Runs the project's own
# lint/build plus the eds audits as a gatekeeper on every PR and push to main.
on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install project dependencies when the repo has them.
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          fi

      # The project's own scripts, if defined (skipped otherwise).
      - name: Lint
        if: hashFiles('package.json') != ''
        run: npm run lint --if-present
      - name: Build
        if: hashFiles('package.json') != ''
        run: npm run build --if-present

      # aem-eds-kit audits - run via npx, no install needed. Each exits
      # non-zero on failures, so a bad PR fails the check.
      - name: Project health (doctor)
        run: npx --yes aem-eds-kit@latest doctor
      - name: Loading & LCP budget
        run: npx --yes aem-eds-kit@latest audit loading
      - name: Security & exploit scan
        run: npx --yes aem-eds-kit@latest audit security
`;

export interface CiScaffoldResult {
	path: string;
	created: boolean;
}

/**
 * Write `.github/workflows/eds.yml` into the project. Never overwrites an
 * existing workflow - returns `created: false` so the caller can report it.
 */
export async function writeCiWorkflow(projectRoot: string): Promise<CiScaffoldResult> {
	const file = path.join(projectRoot, ".github", "workflows", "eds.yml");
	if (existsSync(file)) return { path: CI_WORKFLOW_PATH, created: false };
	await mkdir(path.dirname(file), { recursive: true });
	await writeFile(file, CI_WORKFLOW);
	return { path: CI_WORKFLOW_PATH, created: true };
}
