import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * `xwalk.json` - the crosswalk public config. Enables Universal Editor
 * multi-field support (served to the editor). Generated by default for UE
 * projects; regenerate on demand with `eds scaffold xwalk`.
 */
export const XWALK_CONFIG = {
	public: {
		xwalk: {
			"multi-field": {
				enabled: true,
			},
		},
	},
};

export function buildXwalk(): string {
	return `${JSON.stringify(XWALK_CONFIG, null, 2)}\n`;
}

export interface XwalkResult {
	path: string;
	created: boolean;
}

/** Write `xwalk.json` at the project root. Never overwrites. */
export async function writeXwalk(projectRoot: string): Promise<XwalkResult> {
	const file = path.join(projectRoot, "xwalk.json");
	if (existsSync(file)) return { path: "xwalk.json", created: false };
	await writeFile(file, buildXwalk());
	return { path: "xwalk.json", created: true };
}
